apiVersion: v1
kind: Service
metadata:
  name: bookstore-backend
spec:
  type: LoadBalancer
  ports:
    - port: 4001
      targetPort: 4001 # Ensure this matches the port your backend is listening on
  selector:
    app: bookstore-backend # Ensure this matches the labels of your backend pods